name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker to use Minikube's environment
      run: |
        echo "Configuring Docker to use Minikube's daemon..."
        eval $(minikube docker-env)

    - name: Build backend Docker image
      run: |
        cd backend
        docker build -t fahadnoor1/app-todo-backend:latest .
    
    - name: Build frontend Docker image
      run: |
        cd frontend
        docker build -t fahadnoor1/app-todo-frontend:latest .

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push backend Docker image
      run: docker push fahadnoor1/app-todo-backend:latest

    - name: Push frontend Docker image
      run: docker push fahadnoor1/app-todo-frontend:latest

    - name: Deploy to Minikube
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml

